services:
  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    ports:
      - "3100:3100"
    user: "1003:999" # Give the Loki user the same UID and GID as the host user that owns the mapped volumes
    command: -config.file=/home/loki/loki.yml
    volumes:
      - ./loki:/home/loki
    restart: always

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - "3000:3000"
    user: "1003:999" # Give the Grafana user the same UID and GID as the host user that owns the mapped volumes
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER} # username coming from local .env file
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD} # password coming from local .env file
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    restart: always
