{
 "title": "Sentiment Application Dashboard",
 "time": { "from": "now-15d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Current prediction class distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_label_total{job=\"fastapi_app\"}",
     "legendFormat": "{{label}} prediction"
    }
   ]
  },
  {
   "title": "Confidence of the last prediction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_prediction_confidence{job=\"fastapi_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of daily root endpoint accesses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(root_requests_total{job=\"fastapi_app\"}[1d])",
     "legendFormat": "Root accesses"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_confidence_bucket{label=\"positive\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_confidence_bucket{label=\"negative\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}